#!/bin/sh

if test $# -ne 7
then
    echo " usage : sh $0 [job name] [out file name] [odir] [txyz-conf] [precision] [maxiter] [0 or 1]"
    exit 0
fi

JOB_NAME=$1
OUT_FILE_NAME=$2
SET_OUTPUT_PATH=$3
SET_CONFS=$4
SET_PRECISION=$5
SET_MAXITER=$6
SET_JOB_NUM=$7

echo '#PBS -S /bin/bash'
echo "#PBS -N ${JOB_NAME}_${SET_JOB_NUM}"
echo '#PBS -A HALQCD'
echo '#PBS -q comq'
echo '#PBS -l select=1:ncpus=16:mpiprocs=1:ompthreads=16'
echo '#PBS -l walltime=24:00:00'
echo '#PBS -j oe'
echo "#PBS -o ${OUT_FILE_NAME}_${SET_JOB_NUM}"
echo ''
echo '. /opt/Modules/default/init/bash'
echo ''
echo 'module load gnu/4.4.7 cuda/6.5.14'
echo 'module load mvapich2/1.8.1_gnu_cuda-6.0.37'
echo 'module load boost/1.55_gnu-4.4.7'
echo ''
echo 'cd $PBS_O_WORKDIR'
echo ''
echo 'echo $PBS_NODEFILE'
echo 'cat $PBS_NODEFILE'
echo ''
echo '### This job script is made by T.Miyamoto (2015.06.26)'
echo '###    coulomb gauge fix'
echo '### Using, cuLGT'
echo ''
echo '#########  Parameter Setting #########'
echo '#                                    #'
echo "OUTPUT_PATH=$SET_OUTPUT_PATH"
echo ''
echo "CALC_CONF=$SET_CONFS"
echo ''
echo "PRECISION=$SET_PRECISION"
echo "MAXITER=$SET_MAXITER"
echo "JOB_NUM=$SET_JOB_NUM"
echo ''
echo 'XYZSIZE=96'
echo 'TSIZE=96'
echo ''
echo '## You need change format "config" ! #'
echo '#                                    #'
echo '######################################'
echo 'DIV_TSIZE=$((TSIZE/8+1))'
echo ''
echo 'for CONF in $CALC_CONF'
echo 'do'
echo ''
echo 'echo " @@@SIZE@@@ ${CONF}_t0$((0 + $JOB_NUM)) = `du $OUTPUT_PATH/tmp.mdp/${CONF}_t0$((0 + $JOB_NUM)).mdp`"'
echo 'echo " @@@SIZE@@@ ${CONF}_t0$((2 + $JOB_NUM)) = `du $OUTPUT_PATH/tmp.mdp/${CONF}_t0$((2 + $JOB_NUM)).mdp`"'
echo 'echo " @@@SIZE@@@ ${CONF}_t0$((4 + $JOB_NUM)) = `du $OUTPUT_PATH/tmp.mdp/${CONF}_t0$((4 + $JOB_NUM)).mdp`"'
echo 'echo " @@@SIZE@@@ ${CONF}_t0$((6 + $JOB_NUM)) = `du $OUTPUT_PATH/tmp.mdp/${CONF}_t0$((6 + $JOB_NUM)).mdp`"'
echo ''
echo 'TIME=`date`'
echo 'echo " @@@ GAUGE FIXING START : conf=$CONF : $TIME"'
echo ''
echo '############################   Gauge fix   ###########################'
echo '#                                                                    #'
echo 'sleep 30'
echo './CoulombGaugeFixingSU3_4D_${XYZSIZE}x${DIV_TSIZE} -D 0 \'
echo '--ftype         HEADERONLY \'
echo '--fbasename     $OUTPUT_PATH/tmp.mdp/${CONF}_t \'
echo '--fending       .mdp \'
echo '--fnumberformat 2 \'
echo '--fstartnumber  $((0 + $JOB_NUM)) \'
echo '--fstepnumber   1 \'
echo '--nconf         1 \'
echo '--ormaxiter     $MAXITER \'
echo '--precision     $PRECISION 2>&1 &'
echo 'pid1=$!'
echo ''
echo 'sleep 30'
echo './CoulombGaugeFixingSU3_4D_${XYZSIZE}x${DIV_TSIZE} -D 1 \'
echo '--ftype         HEADERONLY \'
echo '--fbasename     $OUTPUT_PATH/tmp.mdp/${CONF}_t \'
echo '--fending       .mdp \'
echo '--fnumberformat 2 \'
echo '--fstartnumber  $((2 + $JOB_NUM)) \'
echo '--fstepnumber   1 \'
echo '--nconf         1 \'
echo '--ormaxiter     $MAXITER \'
echo '--precision     $PRECISION 2>&1 &'
echo 'pid2=$!'
echo ''
echo 'sleep 30'
echo './CoulombGaugeFixingSU3_4D_${XYZSIZE}x${DIV_TSIZE} -D 2 \'
echo '--ftype         HEADERONLY \'
echo '--fbasename     $OUTPUT_PATH/tmp.mdp/${CONF}_t \'
echo '--fending       .mdp \'
echo '--fnumberformat 2 \'
echo '--fstartnumber  $((4 + $JOB_NUM)) \'
echo '--fstepnumber   1 \'
echo '--nconf         1 \'
echo '--ormaxiter     $MAXITER \'
echo '--precision     $PRECISION 2>&1 &'
echo 'pid3=$!'
echo ''
echo 'sleep 30'
echo './CoulombGaugeFixingSU3_4D_${XYZSIZE}x${DIV_TSIZE} -D 3 \'
echo '--ftype         HEADERONLY \'
echo '--fbasename     $OUTPUT_PATH/tmp.mdp/${CONF}_t \'
echo '--fending       .mdp \'
echo '--fnumberformat 2 \'
echo '--fstartnumber  $((6 + $JOB_NUM)) \'
echo '--fstepnumber   1 \'
echo '--nconf         1 \'
echo '--ormaxiter     $MAXITER \'
echo '--precision     $PRECISION 2>&1 &'
echo 'pid4=$!'
echo ''
echo 'wait $pid1'
echo 'ret_pid1=$?'
echo 'wait $pid2'
echo 'ret_pid2=$?'
echo 'wait $pid3'
echo 'ret_pid3=$?'
echo 'wait $pid4'
echo 'ret_pid4=$?'
echo ''
echo 'if test $ret_pid1 -eq 0 -a $ret_pid2 -eq 0 -a $ret_pid3 -eq 0 -a $ret_pid4 -eq 0'
echo 'then'
echo '   echo "good"'
echo 'else'
echo '   echo "@@@@@@ FATAL ERROR !"'
echo '   echo "@@@@@@ ${CONF}_t0$((0 + $JOB_NUM)).mdp : $ret_pid1"'
echo '   echo "@@@@@@ ${CONF}_t0$((2 + $JOB_NUM)).mdp : $ret_pid2"'
echo '   echo "@@@@@@ ${CONF}_t0$((4 + $JOB_NUM)).mdp : $ret_pid3"'
echo '   echo "@@@@@@ ${CONF}_t0$((6 + $JOB_NUM)).mdp : $ret_pid4"'
echo '   exit 1'
echo 'fi'
echo '#                                                                    #'
echo '######################################################################'
echo ''
echo 'TIME=`date`'
echo 'echo " @@@ GAUGE FIXING END   : conf=$CONF : $TIME"'
echo ''
echo 'done'